### PR TITLE
ClamAV scanning for both submissions and a curation task

### PR DESCRIPTION
**Pull request by pgray64**
Addresses issue #307

**My local clamAV settings had:**
maxFileSize 100M
maxScanSize 100M
StreamMaxLength 100M
MaxZipTypeRcg 3M

Everything else to defaults

**I tested submission uploads on local server and got desired results for the following:**
Test files in Google Drive/Technology/ClamAV Test Files/ 
90 MB DMG file
2-10 MB PDFs
97 MB PDF
Test infected file - upload prevented
88 MB ZIP containing PDFs 

Curation virus scanning task also worked for the above

### CODE REVIEW

**Comment by pgray64** [comment]
For local install of clamAV
`sudo apt-get install clamav clamav-daemon`
Can change limits in `/etc/clamav/clamd.conf `
`sudo service clamav-daemon start`

**Comment by pgray64** [comment]
**Install steps for local server**
Not sure if these are the optimal settings necessarily 

`sudo apt-get install clamav clamav-daemon`  

Run post-install `sudo dpkg-reconfigure clamav-base` 
Handle the configuration file automatically: `Yes` 
Accept defaults EXCEPT:
Socket: `TCP` 
Port: `3310`
Address: `127.0.0.1` 
Max Stream Length: `100` (Mb)
Max File Size: `100M`
Max Scan Size: `100M`
Max zip file reanalyze: `3M`

Update signatures `sudo freshclam`

Restart ClamAV to load changes `sudo service clamav-daemon restart`

**Comment by pgray64** [comment]
I rebuilt my vagrant box without the ClamAV changes to double check, but this branch somehow breaks the upload of .html files while allowing the upload of .htm files. 

Odd that ClamAV bases its behavior on file extensions instead of mime type.

**Comment by alawvt** [comment]
Before pulling this branch, I tried to upload an .html file with a submission and received this error,

htmlantiviruserror
This is surprising because this was before pulling the branch. I have not installed ClamAV (knowingly) on this VM. 
Next, I tried to submit an .htm file and received the same error.

**Comment by alawvt** [comment]
I tried again this morning before testing this branch and could upload both .htm and .html--go figure.  

I installed ClamAV using the setting above. I was able to load a .pdf, .htm, .html file.  I was able to upload the oversize pdf. I still need to test loading an infected file.

@pgray64, please upload a screenshot of the error when trying to upload an .html file.

**Comment by pgray64** [comment]
I rebuilt my vagrant box from clamav branch - both html and htm uploads work fine. Pretty sure I'd done the same steps before. ClamAV still successfully blocks infected test file.

**Pull request merged**
