### PR TITLE
[WIP] Add DSpace 5.4 changes

### PR DESCRIPTION
**Pull request by keithgee**
This branch contains updates to bring our VTechWorks code up-to-date with DSpace 5.4.

Please don't merge this branch yet; it is a work in progress.

I need to
- document the upgrade process
- do more testing
- make sure that our configuration customizations haven't been overwritten
- check that we incorporate any Mirage2 theme changes into our own theme

Please do pull and test if you can make the time!

### CODE REVIEW

**Comment by alawvt** [comment]
@keithgee, I have started testing this and so far it looks good. I have recording results on Google Drive/VTechWorksTeam/Testing/DSpace_5.4_Testing.

**Comment by keithgee** [comment]
Thanks, @alawvt. You are a Life Savers!

**Comment by keithgee** [comment]
@alawvt I added a draft of the upgrade instructions here https://github.com/VTUL/vtechworks/wiki/Upgrading-VTechWorks-for-DSpace-point-releases

**Comment by alawvt** [comment]
@AmberPoo1, please continue testing. Thanks.

**Comment by alawvt** [comment]
@keithgee, thank you for the instructions.

**Comment by alawvt** [comment]
@AmberPoo1, thank you for the testing.

**Comment by alawvt** [comment]
@keithgee, this looks ready for vtechworks.dev.

**Comment by keithgee** [comment]
Thanks, @alawvt.

**Pull request merged**
