### PR TITLE
remove duplicate configurations from local.cfg that are already in dspace.cfg

### PR DESCRIPTION
**Pull request by alawvt**
remove duplicate configurations from local.cfg that are already in dspace.cfg

We will still need to parameterize a few of these. For now, I added the values for the LDE.

### CODE REVIEW

**Comment by alawvt** [comment]
Resolves #590

**Comment by alawvt** [comment]
In this second commit I added a comment with each variable that I think will be changed in Ansible.

**Review by keithgee — CHANGES_REQUESTED** [review]
Something I didn't think of yesterday - I think that it makes sense to leave some things in local.cfg (even if they currently show the same values as in dspace.cfg) if they're ultimately going to be parameterized by the ansible project, since local.cfg is where ansible will modify these parameters. 

Examples of this include db.url and db.password, for example. They're customized by ansible. They could be customized in dspace.cfg (as they were with version 5 of our project) - but I think it makes sense conceptually to have all of the parameters that we're changing locally in one file.

So I think we should take into account what's customized by Ansible, and if a parameter is customized by Ansible, leave it in the local.cfg file. (Even if right now it appears with local.cfg with the default dspace.cfg values - remember we're going to parameterize these things).

**Comment by alawvt** [comment]
@keithgee, thank you very much for thinking about that. I agree that makes sense. I am currently going through the templates to figure out what will need to be changed by Ansible and will add those parameters to local.cfg. So just leave the PR open for now.

**Comment by alawvt** [comment]
I just added a batch of configurations from dspace.cfg from vtechworks production on DSpace 5.

I also added references to 5 variables in site_secrets.yml.

**Comment by alawvt** [comment]
I am closing this PR and continuing instead with #599.

**Pull request closed without merging**
