### PR TITLE
Customized submission form for NDLTD collection

### PR DESCRIPTION
**Pull request by AmberPoo1**
Changed input-forms.xml, added NDLTD form fields, changed
item-submission.xml, added NDLTD steps, add NDLTDDescribeStep.java for
processing submission.

Resolved: #101: Create a custom submission form for the NDLTD
collection /18726

### CODE REVIEW

**Comment by AmberPoo1** [comment]
Hi @alawvt , This is the url of NDLTD collection: http://192.168.60.4/handle/10919/18726

The submission form:
screen shot 2015-12-10 at 5 24 40 pm
screen shot 2015-12-10 at 5 24 56 pm
screen shot 2015-12-10 at 5 25 30 pm


The full item view:
screen shot 2015-12-10 at 5 22 40 pm
screen shot 2015-12-10 at 5 22 51 pm

**Comment by alawvt** [comment]
@AmberPoo1, thank you for working on this form. Please use the spreadsheet in Google Drive/VTechWorks Team/Custom Submission Forms/NDLTDCustomSubmissionForm for the changes. Please implement it with a non-interactive step like OMALS.

**Comment by AmberPoo1** [comment]
@alawvt , the file "DSpaceObject.java" is just as same as the one in the OMALS pull request. I don't know whether two same files will cause a conflict. Let me know if there is any problems. Thanks.

The submission form looks like this now, and default data has been added:
screen shot 2016-01-12 at 4 02 09 pm
screen shot 2016-01-12 at 4 05 57 pm
screen shot 2016-01-12 at 4 06 09 pm

**Comment by AmberPoo1** [comment]
@alawvt . No conflicts now!

**Comment by alawvt** [comment]
@AmberPoo1, thank you for an excellent job.

**Pull request merged**
