### PR TITLE
Code Review Needed - Add Sherpa/Romeo Authority Controls

### PR DESCRIPTION
**Pull request by AmberPoo1**
#174 Add Sherpa/Romeo Authority Controls to Journal Title field so that

users can find policies by journal title

### CODE REVIEW

**Comment by AmberPoo1** [comment]
Hi @amandafrench, @alawvt, could you review this code to see where is the problem? I have changed the configurations but Sherpa/Romeo Authority Controls doesn't work. Thanks.

**Comment by amandafrench** [comment]
Does this feature only work with dc.title.alternative? Try using that field and see if it works. See also this thread -- https://groups.google.com/forum/#!topic/dspace-tech/bS5ngka0hyc 

If that isn't the issue, try assigning to @keithgee or @pgray64 or @alawvt to review.

**Comment by AmberPoo1** [comment]
Sure, thanks, @amandafrench

**Comment by alawvt** [comment]
@AmberPoo1, I pulled and build this. The first time I tried to submit, I got an error, so I removed elements from the list of event.dispatcher consumers in dspace.cfg and rebuilt. I am still getting an error when I try to submit something. Are you able to submit?

**Comment by AmberPoo1** [comment]
@ alawvt, a new pull request #306 was created on this issue.

**Pull request closed without merging**
