### PR TITLE
Fix bug #53: Show lock symbol

### PR DESCRIPTION
**Pull request by AmberPoo1**
Make sure lock symbol appears on restricted items for on-campus users
(as well as off campus users). Customization OverLay

### CODE REVIEW

**Comment by AmberPoo1** [comment]
@amandafrench, @keithgee, @alawvt, one core api  called "AuthorizeManager.java" was changed, I have overlaid it as "dspace/modules/api/src/main/java/org/dspace/authorize/AuthorizeManager.java". Since "api" is a new folder under "modules" and is a basis of many modules, several related "pom.xml" (building files) have to be changed, I have tested it on my machine and it worked.
However, I think this change should be tested carefully before putting it into next version, to make sure the build process would not break or introduce other bugs. @alawvt, Could you test this pull request separately, after testing other two issues please? Thanks a lot!

**Comment by alawvt** [comment]
@AmberPoo1, thank you for creating this customization.   

I just found additional instructions in the DSpace Advanced Customisation page, https://wiki.duraspace.org/display/DSDOC5x/Advanced+Customisation,  

"Additions module

This module was added in DSpace 3.0 and should be used to store dspace-api changes, custom plugins, ... Classes placed in [dspace-source]/dspace/modules/additions will override those located in the dspace-api. This module will be used for all the webapps located in the [dspace-source]/dspace/modules directory and in the command line interface. It is recommended to place all dspace-api changes in this module so the changes made are contained in a single module, making it easier to get an overview of changes made."

@keithgee, do you think we should use this modules/additions/ as part of our customization or the additional  overlay for the api module? If we did use modules/additions, I think we'd have to expand the rsync target. Otherwise we could go with the api overlay.

**Comment by keithgee** [comment]
@alawvt, @AmberPoo1 and I discussed this last week as an option, but perhaps there was difficulty in implementing it. If it works, it seems cleaner than creating and editing .pom files. There's also the option of using the xmlui overlay, I think.

Any of these ways are fine with me as long as it works, doesn't break anything else, and is straightforward (comparatively) to migrate to the next version.

**Comment by keithgee** [comment]
I suspect that this particular change, with the edit to pom.xml in the additions module, could potentially break using modules/additions fir customizations of dspace-api in the future, though. The change here looks to combine 2 different methods; I think I may have miscommunicated the options.

**Comment by alawvt** [comment]
@AmberPoo1, did you attempt this customization with just modules/additions/ and not modules/api/?

**Comment by AmberPoo1** [comment]
Hi @alawvt, @keithgee , thanks! I tried to put the changed api code into additions folder last week, but it didn't work because the changed api code depends on other classes in the original dspace-api.

**Comment by AmberPoo1** [comment]
@alawvt, @keithgee , I think overlay of dspace-apiO("api" in modules folder) is feasible, the changes with pom.xml in addition now is safe and won't break other thing, because this modification means the addition will depend on the overlay of api library. Additionally, if we want to put the changed api code into the addition folder, modification of pom.xml in addition is also necessary.

**Comment by amandafrench** [comment]
Can I just say, I think @kayiwa would be proud of our code review process! Thanks, you guys, for hashing this out.

**Comment by alawvt** [comment]
@AmberPoo1, I was able to use your code changes in modules/additions rather than adding modules/api/ and the changes to the three pom files. Therefore I will close this pull request and pull that one instead.

**Pull request closed without merging**
