### PR TITLE
Cc licenses

### PR DESCRIPTION
**Pull request by amandafrench**
Okay, I think this is finally ready for review: looks pretty good on my LDE. Note that I found and reported a small bug at https://jira.duraspace.org/projects/DS/issues/DS-2954. Please review, @alawvt or @AmberPoo1.

### CODE REVIEW

**Comment by alawvt** [comment]
@amandafrench, I noticed that you deleted my previous commenting out of duplicate keys in dspace/modules/xmlui/src/main/webapp/i18n/messages.xml, lines 134-143. Was that necessary for your work?
```
-<!-- repeats of definitions in Discovery/i18n/messages.xml
-<message key="xmlui.ArtifactBrowser.AdvancedSearch.type_contributor">Contributor</message>
+   <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_contributor">Contributor</message>
    <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_creator">Creator</message>
    <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_description">Description</message>
    <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_relation">Relation</message>
    <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_mime">Mime-Type</message>
    <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_other">Other Contributor</message>
    <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_advisor">Advisor</message>
    <message key="xmlui.ArtifactBrowser.AdvancedSearch.type_department">Department</message>
--->
```

**Comment by alawvt** [comment]
Update: I'm commenting out the definitions in lines 134-143 in this branch and am testing. I will integrate this Pull request with the other that removed modules/xmlui-mirage2/src/main/webapp/themes/vtmirage2/i18n/.

**Comment by alawvt** [comment]
The option "No Creative Commons license" is missing from the dropdown list in the CC license step. I will correct.

**Comment by alawvt** [comment]
@amandafrench, would you look over the changes in dspace/modules/xmlui/src/main/webapp/i18n/messages.xml, lines 2504-2513 and see if they were intentional?  Thanks.

**Comment by amandafrench** [comment]
Will look them over, @alawvt, thx.

**Comment by amandafrench** [comment]
I was apparently working with an outdated copy of messages.xml, one that preceded several customizations to the file: I'm going to close this request, delete the cc-licenses branch, and redo this again on a new branch. Sorry!

**Pull request closed without merging**
