### PR TITLE
Audiovisual submission form

### PR DESCRIPTION
**Pull request by AmberPoo1**
According to “MovingImageCustomSubmissionForm”, adjust the orders of
fields in default submission form; Additional fields will show in the
second page if “Item Type” is “Audio recording” or “Video recording”

### CODE REVIEW

**Comment by AmberPoo1** [comment]
@alawvt, here are some pictures for new submission form:
First Page:
screenshot 2016-07-07 10 59 42
screenshot 2016-07-07 11 00 04

Second Page will show if “Audio recording” or “Video recording” is selected:

screenshot 2016-07-07 11 00 47
screenshot 2016-07-07 11 01 01

**Comment by alawvt** [comment]
@mello99, would you look at these screenshots and comment on the fields and hints? (You don't need to pull and test it.)  I tried to split out the fields in your original mockup into those in the default form (page 1) and those in the video specific form (page 2).

The differences that I see are:

Summary: I neglected to add this to the video specific form. Do you want it added? (mapped to dc.description.notes?)

Rights Statement: This form will have the usual CC License step. Do you want this field in the video specific form?  

Thanks.

**Comment by mello99** [comment]
Ok, the only major thing is that we should **remove the "Rights Statement" section altogether** - the user will have the chance to choose a CC license when they upload the item, which is the more appropriate kind of rights statement for these materials, not a DPLA rights statement. We can leave the "Rights Holder" section where it is - that's important and useful information.

So, yes, the "Rights Statement" section needs to be **removed** - not modified. The form looks great otherwise. There are some issues with the alignment, which are minor, and I would have liked if we'd used different names for our examples (instead of just "Kennedy, John F. Jr." for all of them), but those are very minor issues and don't need to be changed. The only thing that needs to be changed is the removal of the "Rights Statement" section. But yes, it looks excellent! Thanks, take care.

**Comment by alawvt** [comment]
### Video specific fields on page 2

Field: dc.title.alternative 
Label: Other Titles  

Field: dc.identifier.citation 
Label: Citation  

Field: dc.relation.ispartof 
Label: Episode Title   

Field: dc.date.created
Label: Creation Date  

Field: dc.contributor.director
Label: Director(s)  

Field: dc.contributor.editor
Label: Editor(s)   

Field: dc.contributor
Label: Interviewee(s)  

Field: dc.contributor
Label: Interviewer(s) 

Field: dc.contributor
Label: Contributor - Other  

Field: dc.format.extent
Label: Duration  

Field: dc.description.notes
Label: Transcription  

Field: dc.rights.holder
Label: Rights Holder

**Comment by alawvt** [comment]
I reordered the first page of the submission back to the original default submission form and removed the rights field. Attached are screenshots:
Page 1: Default submission form:
videosubmissionpage1
Page 2: If video recording or audio recording is selected:
videosubmissionpage2

**Comment by mello99** [comment]
Hi @alawvt , looks good, thanks!

**Pull request merged**
