### PR TITLE
Footer takedown message updated

### PR DESCRIPTION
**Pull request by pgray64**
Text updated and link goes to correct google sites page
Addresses issue #443

### CODE REVIEW

**Comment by alawvt** [comment]
@pgray64, would you try to stretch the horizontal rule across the whole width of the middle section, as it is on production? It's currently shorter than the other horizontal rules on the page. Otherwise, it looks good.

**Comment by amandafrench** [comment]
Since @pgray64 isn't working this week or next, I think we should merge this pull request without waiting for the horizontal rule to be fixed -- I want to make sure that we have a globally-viewable takedown message deployed next week. We can fix the horizontal rule later.

**Comment by pgray64** [comment]
I'm working today - fixing the footer right now

**Comment by pgray64** [comment]
Footer is fixed
screen shot 2016-12-09 at 12 30 27 pm

**Comment by amandafrench** [comment]
Wonderful, @pgray64 -- thanks!

**Comment by alawvt** [comment]
Looks good!

**Pull request merged**
