### PR TITLE
Add statistics links to home page

### PR DESCRIPTION
**Pull request by keithgee**
This adds:
    - Usage Statistics
    - Search Statistics
    - Workflow Statistics
links on the home page, and makes them available to all users.

This fixes issue #32

### CODE REVIEW

**Comment by amandafrench** [comment]
Hey @keithgee, do you want someone to review this before merge? Maybe @AmberPoo1? Makes sense to me that the two of you would review each other's code, and that either or both of you would review mine and Anne's.

**Comment by keithgee** [comment]
@amandafrench good idea, @AmberPoo1 should review this change if she is available.

**Comment by AmberPoo1** [comment]
Hey @keithgee, @amandafrench, I have reviewed this change. No problem. Thanks.

**Comment by amandafrench** [comment]
Thanks, @AmberPoo1 -- if you like, once you've reviewed it, you can accept the merge by clicking the button. I'll add that to the GitHub wiki.

**Pull request merged**
