### PR TITLE
add facet and search filter customizations

### PR DESCRIPTION
**Pull request by alawvt**
If this works, it will be a long shot. I tried to copy in the changes from discovery.xml on DSpace 5 to DSpace 6. I haven't built DSpace 6, so I was unable to test this. @keithgee, you could test this?Otherwise, do you think I should go on and build a DSpace 6 LDE?

### CODE REVIEW

**Comment by keithgee** [comment]
Related to issue #569

**Comment by keithgee** [comment]
@alawvt Yes, I think it would be helpful for you to have a DSpace 6 VM.

I tried testing, and there were a few problems that wouldn't allow DSpace to start.

One, there appears to be an extra ">" character somewhere near line 844.

`Failure during filter init: Failed to startup the DSpace Service Manager: failure starting up spring service manager: Line 844 in XML document from file [/dspace/config/spring/api/discovery.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 844; columnNumber: 12; cvc-complex-type.2.3: Element 'bean' cannot have character [children], because the type's content type is element-only` 

I removed this character, and still had issues starting DSpace. I haven't looked into the below errors yet.

`
ERROR [localhost-startStop-1] (DSpaceServiceManager.java:230) - Failed to startup the DSpace Service Manager: failure starting up spring service manager: Error creating bean with name 'org.dspace.discovery.configuration.DiscoveryConfigurationService' defined in file [/dspace/config/spring/api/discovery.xml]: Cannot resolve reference to bean 'patentConfiguration' while setting bean property 'map' with key [TypedStringValue: value [10919/72294], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patentConfiguration' defined in file [/dspace/config/spring/api/discovery.xml]: Invocation of init method failed; nested exception is org.dspace.discovery.configuration.DiscoveryConfigurationException: The following tagCloud facet configurations are not present in the search filters list: subject all the tagCloud facets MUST be a part of the search filters list.
java.lang.IllegalStateException: failure starting up spring service manager: Error creating bean with name 'org.dspace.discovery.configuration.DiscoveryConfigurationService' defined in file [/dspace/config/spring/api/discovery.xml]: Cannot resolve reference to bean 'patentConfiguration' while setting bean property 'map' with key [TypedStringValue: value [10919/72294], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patentConfiguration' defined in file [/dspace/config/spring/api/discovery.xml]: Invocation of init method failed; nested exception is org.dspace.discovery.configuration.DiscoveryConfigurationException: The following tagCloud facet configurations are not present in the search filters list: subject all the tagCloud facets MUST be a part of the search filters list.
	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:215)
	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:153)
	at org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener.contextInitialized(DSpaceKernelServletContextListener.java:81)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.discovery.configuration.DiscoveryConfigurationService' defined in file [/dspace/config/spring/api/discovery.xml]: Cannot resolve reference to bean 'patentConfiguration' while setting bean property 'map' with key [TypedStringValue: value [10919/72294], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patentConfiguration' defined in file [/dspace/config/spring/api/discovery.xml]: Invocation of init method failed; nested exception is org.dspace.discovery.configuration.DiscoveryConfigurationException: The following tagCloud facet configurations are not present in the search filters list: subject all the tagCloud facets MUST be a part of the search filters list.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:334)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:384)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:165)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.dspace.servicemanager.spring.SpringServiceManager.startup(SpringServiceManager.java:221)
	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:212)
	... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patentConfiguration' defined in file [/dspace/config/spring/api/discovery.xml]: Invocation of init method failed; nested exception is org.dspace.discovery.configuration.DiscoveryConfigurationException: The following tagCloud facet configurations are not present in the search filters list: subject all the tagCloud facets MUST be a part of the search filters list.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	... 31 more
Caused by: org.dspace.discovery.configuration.DiscoveryConfigurationException: The following tagCloud facet configurations are not present in the search filters list: subject all the tagCloud facets MUST be a part of the search filters list.
	at org.dspace.discovery.configuration.DiscoveryConfiguration.afterPropertiesSet(DiscoveryConfiguration.java:181)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
	... 36 more
Failure during filter init: Failed to startup the DSpace Service Manager: failure starting up spring service manager: Error creating bean with name 'org.dspace.discovery.configuration.DiscoveryConfigurationService' defined in file [/dspace/config/spring/api/discovery.xml]: Cannot resolve reference to bean 'patentConfiguration' while setting bean property 'map' with key [TypedStringValue: value [10919/72294], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patentConfiguration' defined in file [/dspace/config/spring/api/discovery.xml]: Invocation of init method failed; nested exception is org.dspace.discovery.configuration.DiscoveryConfigurationException: The following tagCloud facet configurations are not present in the search filters list: subject all the tagCloud facets MUST be a part of the search filters list.:java.lang.RuntimeException: Failed to startup the DSpace Service Manager: failure starting up spring service manager: Error creating bean with name 'org.dspace.discovery.configuration.DiscoveryConfigurationService' defined in file [/dspace/config/spring/api/discovery.xml]: Cannot resolve reference to bean 'patentConfiguration' while setting bean property 'map' with key [TypedStringValue: value [10919/72294], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patentConfiguration' defined in file [/dspace/config/spring/api/discovery.xml]: Invocation of init method failed; nested exception is org.dspace.discovery.configuration.DiscoveryConfigurationException: The following tagCloud facet configurations are not present in the search filters list: subject all the tagCloud facets MUST be a part of the search filters list.
`

**Review by keithgee — COMMENTED** [review]
Line 842 - extra ">" character.

**Comment by alawvt** [comment]
@soumikgh is working on the DSpace 6 branch of vtlibans. I would like to install that and use it for testing this configuration, as well as the vtlibans DSpace 6 branch itself. Thanks for trying this.

**Comment by alawvt** [comment]
I made some corrections and it is building now and looks ok. I will test it more next week.

**Comment by alawvt** [comment]
@keithgee, it seems ok except "Committee Chair" in the ETD facet is labelled "Advisor" and I couldn't figure out why. Would you mind testing this?

To test, the advanced search filters and facets should match for:

- home page
- etd collections
- patent collection
- any other collection (default settings)

**Pull request merged**
