### PR TITLE
Updates Policies, Help, and About Pages

### PR DESCRIPTION
**Pull request by amandafrench**
Adds copyright policies, ditribution license, likeness permissions, and amendment and withdrawal policies to Policies page, adds advice for link sharing to Help page, and makes a small change concerning handles on the About page

### CODE REVIEW

**Comment by amandafrench** [comment]
Will you review this text, @mello99? Note that I added language about proxies and copyright that essentially says that you can refuse to load something for someone else if you believe they don't have the right to deposit it.

**Comment by mello99** [comment]
Sure, @amandafrench , will do when I come to the office.

**Comment by amandafrench** [comment]
@mello99 I didn't add this to the sprint or the task board, but do please look it over today if you can. Thanks.

**Comment by mello99** [comment]
Ok, the information in there is solid, I made a few minor changes, but that's it. Thanks, merging now.

**Comment by amandafrench** [comment]
Great, thanks, @mello99!

**Pull request merged**
