### PR TITLE
Etd search config

### PR DESCRIPTION
**Pull request by alawvt**
Made additional modifications to search filters and facets after consultation with others.  
Change search facets and filters for ETD and other collections
    Add committee member filter; remove sponsor filter from ETD list; remove mime-type and coverage
    filters from filter lists for all collections; rename ETD Advisor Committee Chair; rename
    ETD level Thesis degree level; comment out duplicate labels in overlay messages.xml.

### CODE REVIEW

**Comment by alawvt** [comment]
need to pull from repository first

**Comment by keithgee** [comment]
Verified
- committee member filter (search for contains 'Smith') (does member set include the chair?)
- sponsor filter removed from ETDs
- mime type filter removed
- coverage filter removed
- committee chair filter (search for contains 'Denbow')
- Thesis degree level facet/filter

**Comment by keithgee** [comment]
@alawvt as you mentioned at the stand-up, this branch contained commits from a WIP by Jing Pu. Instead of merging this pull request, I've cherry-picked your commit 179c34f into the vt_5_x_dev branch on my local environment, tested, and then pushed that single commit back into vt_5_x_dev.

I'll close this pull request without the merge, but your code is in our development branch and we can treat this as complete.

**Comment by alawvt** [comment]
Thank you, @keithgee!

**Pull request closed without merging**
