### PR TITLE
CC licenses - fixes #80 

### LINKED ISSUE #80: Revise text and license options on license page in submission workflow
so that they are clearer

### PR DESCRIPTION
**Pull request by amandafrench**
Accidentally includes some changes to input-forms.xml as well, though really those should be in a different commit. Cleans up a lot of language in messages.xml in addition to making the CC License changes. Assigned to @alawvt for review.

### CODE REVIEW

**Comment by amandafrench** [comment]
I meant to mention that I couldn't test this locally, since my submission process would never let me upload a file, so I couldn't get to the CC license page. Do others have that problem?

**Comment by keithgee** [comment]
I was just able to upload files on two items in my LDE with no problems; on the other hand, my theme is all messed up at the moment.

**Comment by keithgee** [comment]
@amandafrench you can try chown -R tomcat7:tomcat7 /dspace to fix permissions in the asset store and upload directories. Just a first thought. But if you like, post your the error message in mattermost

**Comment by alawvt** [comment]
@amandafrench, please fix the typo in vtmirage2/i18n/messages.xml line 562 
`<message key="xmlui.eperson.shibbLoginFailure.head">Shibboleth authentication Ffiled</message>` in commit  a54a36ce555ce49ddbeeb499fe68ec0b39c1e47e. The rest of it looks good in files. I'll test it once you make that fix.

**Comment by amandafrench** [comment]
Turns out you can't create i18n/messages.xml in dspace/modules/xmlui-mirage2/src/main/webapp/themes/vtmirage2/ -- you have to edit the one in dspace/modules/xmlui/src/main/webapp/i18n. Will close this, revert the commit, and redo.

**Pull request closed without merging**
