### PR TITLE
Customized submission form for OMALS collection

### PR DESCRIPTION
**Pull request by AmberPoo1**
Changed input-forms.xml, added OMALS form fields, changed
item-submission.xml, added OMALS steps, add OMALSDescribeStep.java for
processing submission.

Resolved:  #102: Create a custom submission form for the OMALS
collection /51287

### CODE REVIEW

**Comment by AmberPoo1** [comment]
@alawvt, now the submission pages shows like this:
screen shot 2015-12-03 at 1 03 20 pm
screen shot 2015-12-03 at 3 36 36 pm
And the full item view (contains default metadata fields like "dc.description.degree", etc.):
screen shot 2015-12-03 at 3 23 14 pm

**Comment by alawvt** [comment]
@AmberPoo1, thank you for this impressive start. Here are some refinements:

Committee Chair and Committee Member:
Add last name and first name boxes like the Author field. Add an "Add" box to Committee Chair in case there is a co-chair, since we don't have a place for co-chair.

Subject: Please change the field from dc.subject to dc.subject.cabt.
Below the Subject Keywords textbox, are the instructions, "Enter appropriate subject keywords or phrases." Below that is a link for "Subject Categories," which links to vocabulary:http://{{ansible_fqdn}}//JSON/controlled-vocabulary?vocabularyIdentifier=srsc&metadataFieldName=dc_subject. Please replace the text with "Enter appropriate subject keywords or phrases from the CAB Agricultural and Environmental Thesaurus," with "CAB Agricultural and Environmental Thesaurus" linked to http://www.cabi.org/cabthesaurus/.

I need to check with the folks at the OMALS program about a couple of these fields, so I'll get back to you about them.

**Comment by alawvt** [comment]
Type:
Please add and "Add" box to allow for more than one value for this field.

**Comment by alawvt** [comment]
Some of the fields created have en_US added to the field, for example, dc.type[en_US]. Some do not. Most of them are the fields that are created automatically without user input. The fields which should have en_US added are
- dc.contributor.author
- dc.publisher
- dc.rights
- dc.description.degree
- thesis.degree.grantor

**Comment by alawvt** [comment]
I think we should add the language field, the same as in the regular submission form.

**Comment by AmberPoo1** [comment]
Hi @alawvt, this pull request has been updated. The form is looking like as follows now:
screen shot 2015-12-11 at 11 41 22 am
screen shot 2015-12-11 at 11 41 34 am
screen shot 2015-12-11 at 11 43 26 am

Add the full item view:

screen shot 2015-12-11 at 11 46 44 am
screen shot 2015-12-11 at 11 47 15 am

**Comment by alawvt** [comment]
@mello99, would you look at the resulting metadata in the screenshot above and see if there are any other fields you want added?

**Comment by mello99** [comment]
Excellent job overall! A few comments:

1) If possible, consider adding a drop-down menu to the "Department" field - this could help make the metadata more consistent.

- Also, if users want to list the agricultural research centers they're affiliated with, I think we should create a separate field, e.g., "Agricultural Research Center" (with a drop-down menu of possible agricultural research centers, if that's not too onerous), then map the metadata in this field to "dc.contributor[en_US]".

2) When someone adds a keyword from CABT, will they be permitted to include more than one keyword in the "Subject Keywords" toolbar? I ask because, in the regular VTW submission form, many submitters string all of their keywords together, which we DON'T WANT. For example, they'll type "manure, grain, cows, milk, livestock" on one line; these keywords should be added separately, not collectively.

3) I think you mentioned this earlier, Anne, but is it possible to add automatically-generated metadata for "dc.format.mimetype[en_US]"? We want to include the "dc.format.mimetype[en_US]" field for all VTechWorks items. 

If not, I can add this metadata myself.

a. On a related note, is it possible to add automatically-generated metadata for "dc.type.dcmitype[en_US]"? The DCMI Type Vocabulary can be found here - http://dublincore.org/documents/dcmi-type-vocabulary/ (click #7 - DCMI Type Vocabulary). Very often DCMI Type is correlated with MIME Type (e.g., application/msword and application/pdf usually map to "Text", whereas "application/vnd.ms-excel" and "text/csv" usually map to "Dataset") and "dc.type[en_US]". 

If not, I can add this metadata myself.

4) The stock DLA statement in the "dc.rights[en_US]" field - "The authors of these projects and reports are the copyright holders..." - should be removed since DLA no longer exists. 

First, we should ask the submitter (who is presumably the author) whether he or she holds the copyrights to this item. I know we have the VTUL license form at the end - if the submitter agrees to those terms, maybe that's sufficient to establish copyright ownership. Regardless, if the author holds the copyright and decides not to place the item in the public domain (which he or she may do during the submission process), we should include the following information: 

a. Two discrete "dc.rights[en_US]" fields that read:

i. "In Copyright (InC)"
ii. "This Item is protected by copyright and/or related rights. Some uses of this Item may be deemed fair and permitted by law even without permission from the rights holder(s). For other uses, you need to obtain permission from the rights holder(s)."

Each of these entries should go in a separate "dc.rights[en_US]" field.

5) A "dc.rights.uri" field for all copyrighted items with known copyright holders, which should read: "http://rightsstatements.org/vocab/InC/1.0/"

6) A "dc.rights.holder[en_US]" field, which lists the rights holder's name (typically the author or publisher's name). 

Ideally, we would map this information from the "dc.contributor.author[en_US]" field, but sometimes the authors have transferred their copyrights. If we need to include a question box to determine whether the author holds the copyrights, we could add that, but if you think the VTUL license that people agree to at the end is sufficient, then there's no need for a question box.

If the author does, in fact, hold the copyrights to the item he or she is submitting, his or her name should be mapped to "dc.rights.holder[en_US]." 

If the author does NOT hold the copyrights to the item he or she is submitting, we should ask the author to 1) name the rights holder, 2) indicate whether the rights holder is unknown, or 3) indicate that they've placed the item in the public domain. If the items are in the public domain, steps 4-6 aren't necessary.

7) On our end, I think we need to create a field like "dc.publisher.placeOfpublication", then add "Blacksburg, VA" to this field. I mention this because many citation styles include an item's place of publication.

That's all I can think of for now. The form looks good - I like that you added the CABT option because we need as much control as we can get over the vocabulary. To reiterate, these are just my suggestions; feel free to adopt or disregard them as you see fit. Thanks so much.

**Comment by alawvt** [comment]
@mello99, thank you very much for reviewing this form.

1) I agree that a dropdown list of departments would be preferable. The department list from OMALS includes the research centers in the same list. Since this seems to be a college level program, rather than tightly tied to departments, I'm inclined to use their list, which will at least control the values.
2) The subjects form will work the same way as regular submission form. Users sometimes get it right by using the Add button, but sometimes they don't.
3) We can add dc.format.mimetype and dc.type.dcmitype automatically, but only for a fixed value each. I don't think it is capable (easily) of determining file types. I have added tasks to the Technology backlog to research this.
4) We'll add these two rights fields automatically.
5) We'll add this dc.rights.uri field automatically.
6) We could add the dc.rights.holder field automatically, based on the VTUL license and the value in dc.contributor.author. (A possible out is to put a notice somewhere on the form to contact us if the submitter needs to modify the metadata.)
7) We'll leave this for further discussion. I've added it the Metadata backlog.

**Comment by mello99** [comment]
Sounds good, I like your suggestions very much. Feel free to proceed and let me know if you need anything else :).

**Comment by alawvt** [comment]
dc.contributor.department

Agricultural and Applied Economics
Agricultural, Leadership, and Community Education
Agricultural Technology Program
Animal and Poultry Sciences
Biochemistry
Biological Systems Engineering
Crop and Soil Environmental Sciences
Dairy Science
Entomology
Food Science and Technology
Horticulture
Human Nutrition, Foods, and Exercise
Plant Pathology, Physiology, and Weed Science
Virginia Agricultural Experiment Station
Alson H. Smith Jr. AREC
Eastern Shore AREC
Eastern Virginia AREC
Hampton Roads AREC
Middleburg AREC
Reynolds Homestead AREC
Shenandoah Valley AREC
Southern Piedmont AREC
Southwest Virginia AREC
Tidewater AREC
Virginia Seafood AREC

thesis.degree.discipline
For the last three, the value doesn't include (discontinued)

Education
Environmental Science
Food Safety and Biosecurity
Leadership Studies
Plant Science and Pest Management
Biosecurity, Bio-regulations, and Public Health (discontinued)
Education and Leadership Studies (discontinued)
Food Safety (discontinued)

**Comment by alawvt** [comment]
@AmberPoo1, please use the spreadsheet in Google Drive/VTechWorks Team/Custom Submission Forms/OMALSCustomSubmissionForm for the changes.

**Comment by AmberPoo1** [comment]
@alawvt , I have submitted the latest changes to this pull request. These changes are based on "OMALSCustomSubmission" in Google Driver. Now the submission pages are as follows, only show 1 page:
screen shot 2016-01-09 at 4 03 36 pm
screen shot 2016-01-09 at 4 04 04 pm

And the full item record view:
screen shot 2016-01-09 at 4 09 41 pm
screen shot 2016-01-09 at 4 09 57 pm

**Comment by alawvt** [comment]
@AmberPoo1, the form looks very good. Would you change the link to the CABT to open in a new window or tab instead?  Thanks.

**Comment by alawvt** [comment]
Please add "choose a..." option to each drop-down list and check that it doesn't take that as an acceptable value.

```
<option value="">Choose a State</option>
<option value="Alabama" >Alabama</option>
```

http://www.w3schools.com/tags/att_select_required.asp

**Comment by alawvt** [comment]
@AmberPoo1, It looks great. Thank you!

**Pull request merged**
