### PR TITLE
Adjust video playback for responsive theme

### PR DESCRIPTION
**Pull request by keithgee**

### CODE REVIEW

**Comment by amandafrench** [comment]
Looks good! For future reference try to avoid inline CSS, but I'll let it slide this one time. :)

**Comment by keithgee** [comment]
Phew, that was a close one, @amandafrench. Maybe I should fix it before our production deployment. Time permitting. ;)

**Comment by keithgee** [comment]
Another issue here is that the videojs javascript library isn't actually being used. I made a typo with the filename. 
When I use the correct filename, I actually break more thing than I fix.
In the original implementation of DSpace video at Virginia Tech, it was used primarily because a flash fallback was required for web browsers that didn't yet support HTML 5 video. It also added some styling to the captions.
We only have one video in VTechWorks with captions at this time, and I'm hoping that most of our users now have browsers with HTML5 video support. Do we have analytics for that?
I'm thinking of removing the JavaScript library (in a separate commit)  for now until I can get everything to play better; I'll leave the styling in place.

**Comment by amandafrench** [comment]
We do indeed have browser version analytics, @keithgee -- I set up a custom tab in Google Analytics (to which you have access, Keith) for this, and I'll send you some links and files as well. The short answer, as far as I can tell, is that most of our users do indeed use browsers that support HTML5 video -- they use recent versions of Firefox and Chrome on Windows. We do have a large number of users who are using browsers that don't support the .webm format, but that's different. See http://caniuse.com/#feat=video . More by email.

**Comment by keithgee** [comment]
Thanks @amandafrench.  At the time of the original implementation several years ago, there was a complete split between browsers that supported mp4/h264 and browsers that supported webm. That's why the videos from event capture were encoded in both formats. 
In our implementation - and in html5 video in general - the browser will select a supported format from the list provided in the html.
I appreciate all of the information that you've sent about browser capabilities, and the reports from our analytics. That's very helpful.

**Pull request merged**
