### PR TITLE
#53

### PR DESCRIPTION
**Pull request by AmberPoo1**
Make sure lock symbol appears on restricted items for on-campus
users (as well as off campus users)

### CODE REVIEW

**Comment by AmberPoo1** [comment]
Hi @alawvt , this pull request is for #53:Make sure lock symbol appears on restricted items for on-campus users (as well as off campus users)

**Comment by alawvt** [comment]
@AmberPoo1, please make this customization an overlay by copying the original dspace/dspace-api/src/main/java/org/dspace/authorize/AuthorizeManager.java to dspace/dspace/modules/api/src/main/java/org/dspace/authorize/AuthorizeManager.java and making the changes there. Please copy the original dspace/dspace-xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java to dspace/dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java and making the change there.

**Comment by AmberPoo1** [comment]
Thanks @alawvt. according to the project structure of dspace5,  all of the Java code are maintained outside the "dspace/dspace/modules", e.g., in the dspace-api. I think it's reasonalbe to separate these Java logic codes from the font page codes(scss and xsl) in the folder "dspace/dspace/modules". Maybe we should discuss this issue in the meeting to decide the project code structure, and which codes should be moved.

**Comment by AmberPoo1** [comment]
@alawvt, I will close this pull request and open a new one called "#53_2"

**Pull request closed without merging**
