### PR TITLE
Add off-campus sign-in Link

### PR DESCRIPTION
**Pull request by AmberPoo1**
.Added two .gif files in the vtmirage2, and also changed
navigation.xsl. Add off-campus sign-in link under the static pages
section.

Resolved: #78 Add off-campus sign-in link

### CODE REVIEW

**Comment by AmberPoo1** [comment]
Hi @alawvt, this pull request might be a little hard to test, because it need EZproxy administrator to add vtechwork or test url in its config file.

screen shot 2015-11-07 at 5 03 16 pm

**Comment by alawvt** [comment]
@amandafrench, are you satisfied with this placement of the Off Campus Sign in link in the right navigation bar?
vtwoffcampussignin

**Comment by alawvt** [comment]
@kayiwa, regarding the message that @AmberPoo1, commented about above,

```
To allow http://192.168.60.4/ to be used in a starting point URL, 
your EZproxy administrator must first authorize the hostname of this URL in the config.txt file.

Within this database's section of config.txt, either the following line must be added:

    Host 192.168.60.4

or, alternatively, a RedirectSafe for this host or domain may be appropriate.

After editing config.txt, the EZproxy server must be restarted to make changes take effect.
```
Does ITS need to do anything to enable EZproxy for VTechWorks? Assuming the link that @AmberPoo1 added is ok, it seems like we might need to wait until this is on the server to test.

**Comment by amandafrench** [comment]
Sure, that placement of the logo is good. We're crowding a lot into the sidebar, but what the heck.

**Pull request merged**
