### PR TITLE
Create a new default traditional submission form

### PR DESCRIPTION
**Pull request by AmberPoo1**
According to the requirements in "MovingImageCustomSubmissionForm.xsl”,
changed input-forms.xml.
1. Implements the description fields in 1 page in default tradition
submission form.
2. Changed Value-pairs: “common_identifiers”, “common_types”,  and
“common_iso_languages”, so Value-pairs of “Type” and “Language” also
changed in OMALS, value-pairs of “Language” also changed in NDLTD

Resolved:
#198 Create a new default "traditional" submission form

### CODE REVIEW

**Comment by AmberPoo1** [comment]
**The old traditional submission forms shows:**
old1
old2
old3

**new traditional submission form - see last comment:**

**Accordingly, “Type” and “Language” changes in OMALS, “Language” changes in NDLTD**

**Comment by amandafrench** [comment]
Note: we need to add a comma to the hint for the first name: John F., Jr. -- better metadata practice

**Comment by mello99** [comment]
I think I talked to @alawvt about this; there was an issue with getting the text boxes to remain on the same line; adding too much text to the "hints", even if it seems like a small amount, could easily throw off the text box alignment. I could be wrong, though, and I agree that this is a good metadata practice.

**Comment by mello99** [comment]
Never mind, I deleted my earlier comment; I think I actually recommended that we leave off the comma for suffixes because I had just finished editing the SANREM metadata, which was a behemoth. In short, adding the additional comma caused a lot of stray suffixes to appear when I tried to split names into different columns and rearrange them (e.g., if I wanted to convert "John Smith" to "Smith, John", I would have to use a comma as a delimeter). So, if you took a string like "Kennedy, John F., Jr." and split it into separate columns using a comma delimeter, you would get one column that reads "Kennedy", another column that reads "John F.", and a third column that reads "Jr." I don't know about other use scenarios, but the comma preceding the suffix was disastrous for me when I edited SANREM. Thanks.

**Comment by alawvt** [comment]
I agree that we should leave off the comma for the suffix. That extra comma causes too many headaches to be worth it.

**Comment by alawvt** [comment]
@AmberPoo1, thank you very much. This looks really good and will just need a few corrections. I have highlighted those fields on the spreadsheet in pink and added a comment to those fields with instructions, if necessary.

Once all these changes are good, you can copy the appropriate fields into the NDLTD and OMALS custom submission forms, too.

**Comment by AmberPoo1** [comment]
Thanks, @alawvt

**Comment by AmberPoo1** [comment]
@alawvt, Thank you for the detailed comments in "MovingImageCustomSubmissionForm". New changes have been made according to this updated sheet.

**Comment by amandafrench** [comment]
Whoops, we forgot volume number and issue number - dc.identifier.volume, dc.identifier.issue -- we will probably need to add separate Identifier fields ...

**Comment by alawvt** [comment]
**new traditional submission form**
defaultsubmissionform

**Comment by alawvt** [comment]
@AmberPoo1, thank you, this looks good. I'll add to the backlog, making these changes to the appropriate fields in the OMALS and NDLTD forms.

**Pull request merged**
