### PR TITLE
#37 and #49

### PR DESCRIPTION
**Pull request by AmberPoo1**
#37:Add three static html pages: about, policies and help;
#49:fix “VirginiaTech” logo link

### CODE REVIEW

**Comment by AmberPoo1** [comment]
Hi @alawvt , could you help check these two bugs (staic page contents and “VirginiaTech” logo link) if you have time, thanks!

**Comment by alawvt** [comment]
Yes, I will try to do that today.

**Comment by AmberPoo1** [comment]
Thanks.

**Comment by alawvt** [comment]
The VT logo now links to the VT home page.  

Attached is a screen shot of the About Page.
aboutpage
The About, Policies, and Help pages look good, but I notice a few typos. Since @AmberPoo1 used XHTL, I will edit copies of the markdown versions and save them as XHTML on Google Drive, so it will be easier for her to copy and past them.  

I explained how we would prefer that all customizations be in the dspace/modules folder, so she will rework this branch with (hopefully) only file customizations in that folder.

**Comment by alawvt** [comment]
I would vote to have these page links appear further down the right bar, perhaps after the RSS feeds. These links appear on every page. What do others think?
etdandstaticpages

**Comment by keithgee** [comment]
I agree that the search area should be near the top of the page, and that these new links are pushing it down on the page.

I'm wondering if they'd be better off in the header area. It's where I'd expect to see an "About" link. The way it is now, on mobile phones (a very small percentage of our users) or when the browser is sized quite small, the About/Policies/Help links won't display, because the right bar is hidden until the hamburger is touched or clicked. I'm not sure that there's much room in the header, either, though - the header with these links, along with the bigger new logo, might take up a large percentage of the screen.

Do what you think is best, Anne.

**Pull request closed without merging**
