### PR TITLE
Add Elements configuration

### PR DESCRIPTION
**Pull request by keithgee**
Don't merge/pull this just yet; wait until after the repository tools are installed on production so that these configuration settings aren't duplicated.

This contains configuration changes and settings specific to the Elements repository tools.

### CODE REVIEW

**Comment by keithgee** [comment]
Installation of repository tools has completed, and this can now be merged.

**Comment by amandafrench** [comment]
One small issue: dspace.cfg needs to be changed to have vtechworks.lib.vt.edu/handle etc. be the default URI, not handle.net etc -- remember, we had to do this on efarqa so that the URL in Elements points directly to VTW instead of to the handle server. I can do this today.

**Comment by keithgee** [comment]
I don't know that we should do that on production. It might break other
things. We did that on pprd because the handle prefix is 123456789, which
is a test prefix and doesn't resolve to anything.

**Comment by amandafrench** [comment]
Ah, right, that makes sense. Will not do, and will merge this pull request.

**Comment by keithgee** [comment]
Okay, thanks @amandafrench. But now I'm not sure, because we don't always keep production settings in GitHub anyway. (database passwords, etc.)

This is one of the few things that should have different settings on production and development. This was changed on the PPRD vtechworks because Elements was getting dc.identifier.uri data with http://hdl.handle.net/123456789/[etc] in it, and the links that Elements was creating back to the repository didn't work. Dev and PPRD aren't running handle servers, and 123456789 is fake.

Production is running a handle server, and the http://hdl.handle.net/10919/etc URIs are valid.

Specifically, putting https://vtechworks.lib.vt.edu/handle in the handle.prefix configuration on the production server would cause new items to have https://vtechworks.lib.vt.edu/handle/[etc] in the dc.identifier.uri.

That's okay, but normally that's where we have the handle url(http://hdl.handle.net/etc), and I think that's what @mello99 has specified for dc.identifier.uri.

Longwinded way of saying I think we need to make our system of tracking production/development/local configuration changes and differences as good as our other systems.

**Comment by amandafrench** [comment]
@keithgee Definitely agree with that last point about tracking configuration changes: will book a documentation meeting with @kayiwa when he's in town to get that hammered out. But yes: I agree that the handle.net URI should be the URI of record, as it were -- that's why I wondered a bit about it when you were willing to change it when we were testing efarqa. I was like "Are you sure? Really?" and you were like "Yes!" But I forgot for the moment that those "handles" on dev and pre-prod aren't really handles. So, in short, leave it in dspace.cfg on prod as handle.net etc., the way it is now.

**Pull request merged**
