### PR TITLE
Fix first few letters search problem reported in DS-3996

### PR DESCRIPTION
**Pull request by alawvt**
To resolve Issue #640. This is a close copy of https://github.com/DSpace/DSpace/pull/2191/files, however the file is added to the modules folder as a WAR overlay and the comment has been shorted to fit in 80 characters.

### CODE REVIEW

**Comment by alawvt** [comment]
This seems to work on my LDE. @keithgee, would you have time to test this? I would like to deploy it as a hot fix. Do you think that is reasonable?

**Comment by keithgee** [comment]
@alawvt I trust your leadership and testing in this issue. Yes I think you should prepare and deploy this fix. 

I'm interested in learning from you at a later meeting about how the current re-deployment process works after the VM has already been created; I haven't understand that bit in quite a while.

Thanks!

**Comment by alawvt** [comment]
@keithgee, @soumikgh will deploy this as a hot fix to production. This will require taking down the server for ~30 minutes while he backs up the database and,  I assume,l run `vagrant provision` to add the latest changes.

**Comment by keithgee** [comment]
Should this be deployed to the preproduction instance as well, or is that too much overhead for a small change?

**Comment by keithgee** [comment]
Main thought is I wonder if our update process still works.

**Comment by alawvt** [comment]
@keithgee, I am following our procedure for a hot fix, https://github.com/VTUL/vtechworks/wiki/08.-Fixing-urgent-problems-on-production-(hotfixes). I do plan to have  other changes soon, which I will take through the normal deployment procedure, so I thought this would be sufficient for now.

**Pull request merged**
