### PR TITLE
Remove file description field from submission forms

### PR DESCRIPTION
**Pull request by AmberPoo1**
Remove File Description field from upload step and file edit page.
Modified UploadWithEmbargoStep.java and EditFileStep.java

Resolved:  #192 In the submissions form, remove File Description field
from the Upload step

### CODE REVIEW

**Comment by AmberPoo1** [comment]
**Before this change, the file upload page and file edit page show like this:**

old
old2

**After this change:**
new
new2

**Comment by amandafrench** [comment]
I just recently remembered that we wanted some language on the default submission form about desirable preservation formats, specifically using PDF/A instead of PDF. Let's not merge this pull request until we've got that in place. If I get time this week maybe I can meet with Melissa about it, but more likely it'll be next week when @alawvt is back.

**Comment by amandafrench** [comment]
Added language in messages.xml about PDF/A; reassigning to @alawvt for review.

**Comment by alawvt** [comment]
@AmberPoo1, thank you very much for this code change.

**Pull request merged**
