### PR TITLE
Change Green Sherpa Romeo message

### PR DESCRIPTION
**Pull request by mello99**
Request to add changes to the "green" Sherpa/Romeo message in the "messages.xml" file.

### CODE REVIEW

**Comment by amandafrench** [comment]
I think this needs to be more positive about what _can_ for sure be deposited. Also the extra "More info" link is redundant.

**Comment by mello99** [comment]
Added a new message - https://github.com/VTUL/vtechworks/pull/257/commits/3d263cbc3fc035f7e7f69b8d2913d1cea4b32892. The message is long, unfortunately; it's difficult to explain this concept in a very short sentence!

**Comment by amandafrench** [comment]
Take a look at this language, @mello99, and see if it works for you!

**Comment by mello99** [comment]
Looks good, just merged pull request.

**Pull request merged**
